title: Jia Hong's website
description: >- # this means to ignore newlines until "baseurl:"
  Hello, there! I'm Jia Hong. I'm pretty new to tech in general, so I'm excited to be here.
  Welcome, to my blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  YJH16120

# Build settings
theme: minima
plugins:
  - jekyll-feed
