title: Jia's Hong website
description: >- # this means to ignore newlines until "baseurl:"
  Wow look at this, someone decided to take a look at my website. Why hello there,
  this site is made by me using Jekyll. Feel free to take a look around.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  YJH16120

# Build settings
theme: minima
plugins:
  - jekyll-feed
