title: AlphabetsAlphabets' Blog
email: yapjiahong-p@proton.me
description: >-
  For sharing my use cases, and stuff I create that helps myself. 
baseurl: ""
url: ""
github_username: AlphabetsAlphabets

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
